server:
  port: ${global.admin-base-center.port}
spring:
  profiles:
    include: global
  application:
    name: ${global.admin-base-center.server-name}
  cloud:
    nacos:
      discovery:
        server-addr: ${global.nacos.server-addr}
  boot:
    admin:
      notify:
        mail:
          to: 644543260@qq.com
          from: "Spring Boot <locahost@sina.com>"
      context-path: /admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: warn