server:
  port: ${global.admin-service-provider.port}
spring:
  profiles:
    include: global
  application:
    name: ${global.admin-service-provider.server-name}
  cloud:
    nacos:
      discovery:
        server-addr: ${global.nacos.server-addr}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: warn